### ISSUE TITLE
Problem : Tkinter

### ISSUE THREAD

**Issue by AraFurieux** [TheSph1nx/Spacenet#2]
Hello ! I'm on parrot sec ... And i have a problem ... The server work ... But the builder have a problem ...
┌─[✗]─[root@parrot]─[/home/boris/Spacenet/Software/Agent/Builder]
└──╼ #python builder.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1550, in __call__
    return self.func(*args)
  File "builder.py", line 311, in onselect
    index = int(w.curselection()[0])
IndexError: tuple index out of range

....
I have install Tkinter ... Can you help me please ?
Thank you !

**Comment by AraFurieux** [comment]
And when i build : AttributeError: 'tuple' object has no attribute 'replace'
257 INFO: PyInstaller: 3.3.1
257 INFO: Python: 2.7.15+
257 INFO: Platform: Linux-4.18.0-parrot10-amd64-x86_64-with-Parrot-4.3-stable
263 INFO: wrote /home/boris/Spacenet/Software/Agent/Builder/homeborisSpacenetSoftwareAgentagent.spec
263 DEBUG: Testing for UPX ...
357 INFO: UPX is available.
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 162, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script '/home/boris/Spacenet/Software/Agent/Builder/homeborisSpacenetSoftwareAgentagent.py' not found
